-- TAMBOV VK Bot SQL
-- Run this in the SAME Supabase project used by the site and Vercel bot.
-- Safe to run multiple times.

create table if not exists public.vk_links (
  vk_user_id text primary key,
  site_user_id text not null,
  email text not null,
  nickname text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists vk_links_site_user_id_key
  on public.vk_links (site_user_id);

create table if not exists public.vk_link_codes (
  code text primary key,
  site_user_id text not null,
  email text not null,
  nickname text,
  status text not null default 'pending' check (status in ('pending', 'used', 'expired')),
  used_by_vk_user_id text,
  used_at timestamptz,
  expires_at timestamptz not null default (now() + interval '15 minutes'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists vk_link_codes_site_user_id_idx
  on public.vk_link_codes (site_user_id, created_at desc);

create index if not exists vk_link_codes_status_expires_idx
  on public.vk_link_codes (status, expires_at);

create table if not exists public.vk_report_sessions (
  session_key text primary key,
  vk_user_id text not null,
  peer_id text not null,
  step text not null,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists vk_report_sessions_updated_at_idx
  on public.vk_report_sessions (updated_at);

create table if not exists public.vk_group_bindings (
  peer_id text primary key,
  group_type text not null,
  title text,
  set_by_vk_user_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$
declare
  c record;
begin
  for c in
    select conname
    from pg_constraint
    where conrelid = 'public.vk_group_bindings'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%group_type%'
  loop
    execute format('alter table public.vk_group_bindings drop constraint %I', c.conname);
  end loop;
end $$;

alter table public.vk_group_bindings
  add constraint vk_group_bindings_group_type_check
  check (group_type in ('reports', 'staff', 'candidates', 'general', 'ai', 'nomod', 'off'));

create index if not exists vk_group_bindings_type_idx
  on public.vk_group_bindings (group_type);

create table if not exists public.vk_staff_roles (
  vk_user_id text primary key,
  role text not null check (role in ('gm', 'zgm', 'curator', 'km', 'moderator')),
  title text,
  note text,
  granted_by_vk_user_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists vk_staff_roles_role_idx
  on public.vk_staff_roles (role);

create table if not exists public.vk_moderation_actions (
  id text primary key,
  peer_id text,
  target_vk_user_id text not null,
  actor_vk_user_id text not null,
  action_type text not null check (action_type in (
    'oral_warn',
    'warn',
    'strict_warn',
    'mute',
    'ban',
    'private_room_block',
    'global_block',
    'reset'
  )),
  duration_text text,
  duration_minutes integer,
  reason text,
  status text not null default 'active' check (status in ('active', 'cancelled', 'expired')),
  cancelled_by_vk_user_id text,
  cancelled_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists vk_moderation_actions_target_idx
  on public.vk_moderation_actions (target_vk_user_id, created_at desc);

create index if not exists vk_moderation_actions_actor_idx
  on public.vk_moderation_actions (actor_vk_user_id, created_at desc);

create table if not exists public.vk_google_sheet_events (
  id bigint generated by default as identity primary key,
  sheet_name text,
  row_number integer,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'received',
  error_message text,
  created_at timestamptz not null default now()
);

create index if not exists vk_google_sheet_events_sheet_row_idx
  on public.vk_google_sheet_events (sheet_name, row_number);

create table if not exists public.vk_application_decisions (
  id text primary key,
  peer_id text,
  row_number integer not null,
  sheet_name text,
  actor_vk_user_id text not null,
  verdict text not null,
  reason text,
  previous_verdict text,
  spreadsheet_url text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists vk_application_decisions_row_idx
  on public.vk_application_decisions (sheet_name, row_number, created_at desc);

create index if not exists vk_application_decisions_actor_idx
  on public.vk_application_decisions (actor_vk_user_id, created_at desc);

create index if not exists vk_application_decisions_created_at_idx
  on public.vk_application_decisions (created_at desc);

create or replace function public.set_updated_at_now()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_vk_links_updated_at on public.vk_links;
create trigger set_vk_links_updated_at
before update on public.vk_links
for each row execute function public.set_updated_at_now();

drop trigger if exists set_vk_link_codes_updated_at on public.vk_link_codes;
create trigger set_vk_link_codes_updated_at
before update on public.vk_link_codes
for each row execute function public.set_updated_at_now();

drop trigger if exists set_vk_report_sessions_updated_at on public.vk_report_sessions;
create trigger set_vk_report_sessions_updated_at
before update on public.vk_report_sessions
for each row execute function public.set_updated_at_now();

drop trigger if exists set_vk_group_bindings_updated_at on public.vk_group_bindings;
create trigger set_vk_group_bindings_updated_at
before update on public.vk_group_bindings
for each row execute function public.set_updated_at_now();

drop trigger if exists set_vk_staff_roles_updated_at on public.vk_staff_roles;
create trigger set_vk_staff_roles_updated_at
before update on public.vk_staff_roles
for each row execute function public.set_updated_at_now();

alter table public.vk_links disable row level security;
alter table public.vk_link_codes enable row level security;
alter table public.vk_report_sessions disable row level security;
alter table public.vk_group_bindings disable row level security;
alter table public.vk_staff_roles disable row level security;
alter table public.vk_moderation_actions disable row level security;
alter table public.vk_google_sheet_events disable row level security;
alter table public.vk_application_decisions disable row level security;

grant usage on schema public to anon, authenticated, service_role;
grant select, insert, update, delete on public.vk_links to service_role;
grant select on public.vk_links to authenticated;
grant select, insert, update, delete on public.vk_link_codes to authenticated, service_role;
grant select, insert, update, delete on public.vk_report_sessions to anon, authenticated, service_role;
grant select, insert, update, delete on public.vk_group_bindings to anon, authenticated, service_role;
grant select, insert, update, delete on public.vk_staff_roles to anon, authenticated, service_role;
grant select, insert, update, delete on public.vk_moderation_actions to anon, authenticated, service_role;
grant select, insert, update, delete on public.vk_google_sheet_events to anon, authenticated, service_role;
grant usage, select on sequence public.vk_google_sheet_events_id_seq to anon, authenticated, service_role;
grant select, insert, update, delete on public.vk_application_decisions to anon, authenticated, service_role;

create table if not exists public.vk_ai_memory (
  vk_user_id text primary key,
  display_name text,
  memory jsonb not null default '{}'::jsonb,
  summary text,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.vk_ai_messages (
  id bigint generated by default as identity primary key,
  vk_user_id text not null,
  peer_id text,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.vk_ai_image_generations (
  id bigint generated by default as identity primary key,
  vk_user_id text not null,
  peer_id text,
  prompt text not null,
  image_url text,
  vk_attachment text,
  status text not null default 'created',
  error_message text,
  created_at timestamptz not null default now()
);

create index if not exists vk_ai_messages_user_created_idx
  on public.vk_ai_messages (vk_user_id, created_at desc);

create index if not exists vk_ai_image_generations_user_created_idx
  on public.vk_ai_image_generations (vk_user_id, created_at desc);

drop trigger if exists set_vk_ai_memory_updated_at on public.vk_ai_memory;
create trigger set_vk_ai_memory_updated_at
before update on public.vk_ai_memory
for each row execute function public.set_updated_at_now();

alter table public.vk_ai_memory disable row level security;
alter table public.vk_ai_messages disable row level security;
alter table public.vk_ai_image_generations disable row level security;

grant select, insert, update, delete on public.vk_ai_memory to anon, authenticated, service_role;
grant select, insert, update, delete on public.vk_ai_messages to anon, authenticated, service_role;
grant usage, select on sequence public.vk_ai_messages_id_seq to anon, authenticated, service_role;
grant select, insert, update, delete on public.vk_ai_image_generations to anon, authenticated, service_role;
grant usage, select on sequence public.vk_ai_image_generations_id_seq to anon, authenticated, service_role;

drop policy if exists "vk_link_codes_user_select_own" on public.vk_link_codes;
create policy "vk_link_codes_user_select_own"
on public.vk_link_codes
for select
to authenticated
using (site_user_id = auth.uid()::text);

drop policy if exists "vk_link_codes_user_insert_own" on public.vk_link_codes;
create policy "vk_link_codes_user_insert_own"
on public.vk_link_codes
for insert
to authenticated
with check (site_user_id = auth.uid()::text);

drop policy if exists "vk_link_codes_user_update_own_pending" on public.vk_link_codes;
create policy "vk_link_codes_user_update_own_pending"
on public.vk_link_codes
for update
to authenticated
using (site_user_id = auth.uid()::text and status = 'pending')
with check (site_user_id = auth.uid()::text);

-- Fixed bot owner for this build.
insert into public.vk_staff_roles (
  vk_user_id,
  role,
  title,
  note,
  granted_by_vk_user_id,
  updated_at
)
values (
  '628466808',
  'gm',
  'ГМ',
  'Владелец бота',
  'system',
  now()
)
on conflict (vk_user_id) do update set
  role = excluded.role,
  title = excluded.title,
  note = excluded.note,
  updated_at = now();

notify pgrst, 'reload schema';

-- v48: report decisions and moderator career ladder.
create table if not exists public.moderator_careers (
  site_user_id text primary key,
  email text,
  nickname text,
  vk_user_id text,
  rank text not null default 'junior_moderator'
    check (rank in ('junior_moderator', 'moderator', 'senior_moderator', 'km', 'zgm', 'gm')),
  active boolean not null default true,
  appointed_at timestamptz not null default now(),
  rank_started_at timestamptz not null default now(),
  source text not null default 'site',
  source_sheet text,
  source_row integer,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists moderator_careers_vk_user_id_key
  on public.moderator_careers (vk_user_id)
  where vk_user_id is not null and vk_user_id <> '';
create index if not exists moderator_careers_rank_idx
  on public.moderator_careers (rank, active, rank_started_at);

create table if not exists public.moderator_report_reviews (
  report_id text primary key,
  site_user_id text,
  email text,
  vk_user_id text,
  requested_status text,
  final_status text,
  xp integer not null default 0,
  verdict text not null default 'pending'
    check (verdict in ('pending', 'approved', 'rejected')),
  reason_code text,
  reason_text text,
  actor_vk_user_id text,
  actor_site_user_id text,
  source text,
  staff_peer_id text,
  staff_conversation_message_id bigint,
  staff_message_text text,
  staff_attachments text,
  notification_status text,
  notification_error text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists moderator_report_reviews_user_idx
  on public.moderator_report_reviews (site_user_id, created_at desc);
create index if not exists moderator_report_reviews_verdict_idx
  on public.moderator_report_reviews (verdict, created_at desc);

create table if not exists public.moderator_promotion_alerts (
  id text primary key,
  site_user_id text not null,
  vk_user_id text,
  from_rank text not null,
  to_rank text not null,
  eligibility_type text not null check (eligibility_type in ('regular', 'early')),
  days_on_rank integer not null default 0,
  approved_reports integer not null default 0,
  high_reports integer not null default 0,
  status text not null default 'pending'
    check (status in ('pending', 'promoted', 'postponed', 'cancelled')),
  staff_peer_id text,
  staff_conversation_message_id bigint,
  decided_by_vk_user_id text,
  decided_at timestamptz,
  remind_after timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists moderator_promotion_alerts_one_pending_idx
  on public.moderator_promotion_alerts (site_user_id, from_rank, to_rank)
  where status = 'pending';
create index if not exists moderator_promotion_alerts_status_idx
  on public.moderator_promotion_alerts (status, remind_after, created_at);

drop trigger if exists set_moderator_careers_updated_at on public.moderator_careers;
create trigger set_moderator_careers_updated_at before update on public.moderator_careers
for each row execute function public.set_updated_at_now();
drop trigger if exists set_moderator_report_reviews_updated_at on public.moderator_report_reviews;
create trigger set_moderator_report_reviews_updated_at before update on public.moderator_report_reviews
for each row execute function public.set_updated_at_now();
drop trigger if exists set_moderator_promotion_alerts_updated_at on public.moderator_promotion_alerts;
create trigger set_moderator_promotion_alerts_updated_at before update on public.moderator_promotion_alerts
for each row execute function public.set_updated_at_now();

alter table public.moderator_careers enable row level security;
alter table public.moderator_report_reviews enable row level security;
alter table public.moderator_promotion_alerts disable row level security;

drop policy if exists "moderator_careers_read_own" on public.moderator_careers;
create policy "moderator_careers_read_own" on public.moderator_careers
for select to authenticated using (site_user_id = auth.uid()::text);
drop policy if exists "moderator_report_reviews_read_own" on public.moderator_report_reviews;
create policy "moderator_report_reviews_read_own" on public.moderator_report_reviews
for select to authenticated using (site_user_id = auth.uid()::text);

grant usage on schema public to authenticated, service_role;
grant select on public.moderator_careers to authenticated;
grant select on public.moderator_report_reviews to authenticated;
grant select, insert, update, delete on public.moderator_careers to service_role;
grant select, insert, update, delete on public.moderator_report_reviews to service_role;
grant select, insert, update, delete on public.moderator_promotion_alerts to service_role;

notify pgrst, 'reload schema';
