-- TAMBOV VK Bot v35: xAI/Grok memory and image generations.
-- Safe to run multiple times.

create table if not exists public.vk_ai_memory (
  vk_user_id text primary key,
  display_name text,
  memory jsonb not null default '{}'::jsonb,
  summary text,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.vk_ai_messages (
  id bigint generated by default as identity primary key,
  vk_user_id text not null,
  peer_id text,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.vk_ai_image_generations (
  id bigint generated by default as identity primary key,
  vk_user_id text not null,
  peer_id text,
  prompt text not null,
  image_url text,
  vk_attachment text,
  status text not null default 'created',
  error_message text,
  created_at timestamptz not null default now()
);

create index if not exists vk_ai_messages_user_created_idx
  on public.vk_ai_messages (vk_user_id, created_at desc);

create index if not exists vk_ai_image_generations_user_created_idx
  on public.vk_ai_image_generations (vk_user_id, created_at desc);

drop trigger if exists set_vk_ai_memory_updated_at on public.vk_ai_memory;
create trigger set_vk_ai_memory_updated_at
before update on public.vk_ai_memory
for each row execute function public.set_updated_at_now();

alter table public.vk_ai_memory disable row level security;
alter table public.vk_ai_messages disable row level security;
alter table public.vk_ai_image_generations disable row level security;

grant select, insert, update, delete on public.vk_ai_memory to anon, authenticated, service_role;
grant select, insert, update, delete on public.vk_ai_messages to anon, authenticated, service_role;
grant usage, select on sequence public.vk_ai_messages_id_seq to anon, authenticated, service_role;
grant select, insert, update, delete on public.vk_ai_image_generations to anon, authenticated, service_role;
grant usage, select on sequence public.vk_ai_image_generations_id_seq to anon, authenticated, service_role;
