-- CH89 VK Bot v5 SQL
-- Run this in the SAME Supabase project used by the site and Vercel bot.
-- Safe to run multiple times.

create table if not exists public.vk_links (
  vk_user_id text primary key,
  site_user_id text not null,
  email text not null,
  nickname text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists vk_links_site_user_id_key
  on public.vk_links (site_user_id);

create table if not exists public.vk_report_sessions (
  session_key text primary key,
  vk_user_id text not null,
  peer_id text not null,
  step text not null,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists vk_report_sessions_updated_at_idx
  on public.vk_report_sessions (updated_at);

create table if not exists public.vk_group_bindings (
  peer_id text primary key,
  group_type text not null check (group_type in ('reports', 'staff', 'general', 'ai', 'off')),
  title text,
  set_by_vk_user_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists vk_group_bindings_type_idx
  on public.vk_group_bindings (group_type);

create table if not exists public.vk_staff_roles (
  vk_user_id text primary key,
  role text not null check (role in ('gm', 'zgm', 'curator', 'km', 'moderator')),
  title text,
  note text,
  granted_by_vk_user_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists vk_staff_roles_role_idx
  on public.vk_staff_roles (role);

create table if not exists public.vk_moderation_actions (
  id text primary key,
  peer_id text,
  target_vk_user_id text not null,
  actor_vk_user_id text not null,
  action_type text not null check (action_type in (
    'oral_warn',
    'warn',
    'strict_warn',
    'mute',
    'ban',
    'private_room_block',
    'global_block',
    'reset'
  )),
  duration_text text,
  duration_minutes integer,
  reason text,
  status text not null default 'active' check (status in ('active', 'cancelled', 'expired')),
  cancelled_by_vk_user_id text,
  cancelled_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists vk_moderation_actions_target_idx
  on public.vk_moderation_actions (target_vk_user_id, created_at desc);

create index if not exists vk_moderation_actions_actor_idx
  on public.vk_moderation_actions (actor_vk_user_id, created_at desc);

create table if not exists public.vk_google_sheet_events (
  id bigint generated by default as identity primary key,
  sheet_name text,
  row_number integer,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'received',
  error_message text,
  created_at timestamptz not null default now()
);

create index if not exists vk_google_sheet_events_sheet_row_idx
  on public.vk_google_sheet_events (sheet_name, row_number);

create or replace function public.set_updated_at_now()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_vk_links_updated_at on public.vk_links;
create trigger set_vk_links_updated_at
before update on public.vk_links
for each row execute function public.set_updated_at_now();

drop trigger if exists set_vk_report_sessions_updated_at on public.vk_report_sessions;
create trigger set_vk_report_sessions_updated_at
before update on public.vk_report_sessions
for each row execute function public.set_updated_at_now();

drop trigger if exists set_vk_group_bindings_updated_at on public.vk_group_bindings;
create trigger set_vk_group_bindings_updated_at
before update on public.vk_group_bindings
for each row execute function public.set_updated_at_now();

drop trigger if exists set_vk_staff_roles_updated_at on public.vk_staff_roles;
create trigger set_vk_staff_roles_updated_at
before update on public.vk_staff_roles
for each row execute function public.set_updated_at_now();

alter table public.vk_links disable row level security;
alter table public.vk_report_sessions disable row level security;
alter table public.vk_group_bindings disable row level security;
alter table public.vk_staff_roles disable row level security;
alter table public.vk_moderation_actions disable row level security;
alter table public.vk_google_sheet_events disable row level security;

grant usage on schema public to anon, authenticated, service_role;
grant select, insert, update, delete on public.vk_links to anon, authenticated, service_role;
grant select, insert, update, delete on public.vk_report_sessions to anon, authenticated, service_role;
grant select, insert, update, delete on public.vk_group_bindings to anon, authenticated, service_role;
grant select, insert, update, delete on public.vk_staff_roles to anon, authenticated, service_role;
grant select, insert, update, delete on public.vk_moderation_actions to anon, authenticated, service_role;
grant select, insert, update, delete on public.vk_google_sheet_events to anon, authenticated, service_role;
grant usage, select on sequence public.vk_google_sheet_events_id_seq to anon, authenticated, service_role;

-- Fixed bot owner for this build.
insert into public.vk_staff_roles (
  vk_user_id,
  role,
  title,
  note,
  granted_by_vk_user_id,
  updated_at
)
values (
  '628466808',
  'gm',
  'ГМ',
  'Владелец бота',
  'system',
  now()
)
on conflict (vk_user_id) do update set
  role = excluded.role,
  title = excluded.title,
  note = excluded.note,
  updated_at = now();

notify pgrst, 'reload schema';
